on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check for release
        uses: actions/github-script@v6.0.0
        id: release_status
        with:
          script: |
            const tag = github.ref_name;

            try {
              const { id } = await github.releases.getReleaseByTag({ ...context.repo, tag });

              core.setOutput("release_id", id);
              core.setOutput("exists", true);
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

      - name: Delete existing release
        if: steps.release_status.outputs.exists == 'true'
        uses: actions/github-script@v6.0.0
        with:
          script: |
            await github.releases.deleteRelease({ ...context.repo, release_id: ${{ steps.release_status.outputs.release_id }} });

      - name: Get changelog entry
        uses: mindsers/changelog-reader-action@v2.0.0
        id: changelog_reader
        with:
          version: ${{ steps.tag_name.outputs.current_version }}

      - uses: softprops/action-gh-release@v0.1.14
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}
          generate_release_notes: true
