name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://github.com/xt0rted-test/release-environment/blob/main/README.md

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Run a one-line script
        run: echo ${{ secrets.ENVIRONMENT_SECRET }}
